#!/usr/bin/env python3
"""library.json -> a reading digest: every cluster, then every paper in full.

DIFFERENT DOCUMENT FROM THE LITERATURE REVIEW, deliberately. `make_review.py`
produces the review that IS the taxonomy -- build.py reads the newest
`*_literature_review.md` out of outputs/ to learn which paper sits in which topic,
so that file is a contract and shows one Abstract per paper to stay readable.

This is for reading rather than for the build. Nothing parses it. It shows the
clusters first, so the shape of the collection can be taken in at once, and then
every paper with the three sections the review leaves out: Summary, Key points and
Limitations.

The filename deliberately does NOT match `*_literature_review.md`. A second file
matching that glob in outputs/ would be picked up by `newest_review()` and become
the taxonomy the build reads.

    python3 scripts/make_digest.py                  # -> reports/<date>_reading_digest.md
    python3 scripts/make_digest.py --out outputs

Standard library only.
"""
from __future__ import annotations

import argparse
import json
import re
import sys
from datetime import date
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
import build  # noqa: E402

ROOT = build.ROOT


def resolve_out(arg: str) -> Path:
    """Resolved against the AREA, like make_review.py's --out."""
    p = Path(arg)
    return p if p.is_absolute() else ROOT / p


def slug(paper: dict) -> str:
    """A stable in-document anchor, so the cluster list can link to the entry."""
    return "p-" + re.sub(r"[^a-z0-9]+", "-", (paper.get("id") or "").lower()).strip("-")


def cite(p: dict) -> str:
    """`first_author` is ALREADY a formatted citation string -- "Abramson, J. et
    al." -- built by build.py from the registered byline. Re-deriving a surname
    from it produced "al. et al.", because the last whitespace token of
    "Abramson, J. et al." is "al.". Use it as it comes."""
    who = (p.get("first_author") or "").strip()
    if not who:
        au = p.get("authors") or []
        who = (au[0] + (" et al." if len(au) > 1 else "")) if au else "Author not recorded"
    return f"{who} ({p.get('year') or 'n.d.'})"


def esc(s: str) -> str:
    return (s or "").strip()


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--out", default="reports",
                    help="directory to write into (default: reports/, a draft)")
    ap.add_argument("--date", default=date.today().isoformat())
    args = ap.parse_args()

    lib_path = build.DATA / "library.json"
    if not lib_path.exists():
        print("make_digest: data/library.json not found -- run `make build` first.",
              file=sys.stderr)
        return 1
    lib = json.loads(lib_path.read_text(encoding="utf-8"))
    cfg = build.load_project()
    papers = lib["papers"]
    by_topic: dict[str, list] = {}
    for p in papers:
        by_topic.setdefault(p.get("topic") or "(unfiled)", []).append(p)
    # Newest first inside a topic, then by author, so the order is determined.
    for v in by_topic.values():
        v.sort(key=lambda p: (-(p.get("year") or 0), cite(p)))

    tax = lib.get("taxonomy") or []
    n_top = sum(len(part["topics"]) for part in tax)
    unfiled = [p for p in papers if not p.get("topic")]

    L: list[str] = []
    A = L.append
    A(f"# {cfg.get('name','Library')} — reading digest: {len(papers)} papers")
    A("")
    A(f"> {args.date} · {len(papers)} papers · {n_top} topics in {len(tax)} parts · "
      f"data as of {lib.get('data_as_of','unknown')}")
    A("")
    A("## How to read this")
    A("")
    A("Part 1 is every cluster: what it is for, and which papers are in it. Part 2 is "
      "every paper in full — the summary, the specific claims, and what the paper does "
      "**not** support.")
    A("")
    A("The summaries are **paraphrases written by reading the papers, not quotations, "
      "and this document is not a source.** Every entry links its DOI; quote the paper, "
      "never this. A paper being here is not an endorsement — where the notes record "
      "scepticism it is preserved as readily as praise.")
    A("")
    A(f"The clustering lives in `outputs/` and is the same one the browsable page uses. "
      f"This file is generated by `scripts/make_digest.py`; nothing reads it.")
    A("")

    # ── Part 1 ───────────────────────────────────────────────────────────────
    A("---")
    A("")
    A("# Part 1 — The clusters")
    A("")
    for part in tax:
        A(f"## {part['letter']}. {part['name']}")
        A("")
        for t in part["topics"]:
            entries = by_topic.get(t["name"], [])
            A(f"### {t['name']}")
            A("")
            A(f"*{t.get('count', len(entries))} papers.* {esc(t.get('description'))}")
            A("")
            for p in entries:
                A(f"- [{esc(p.get('title')) or p['source']}](#{slug(p)}) — "
                  f"{cite(p)}, *{esc(p.get('venue')) or 'venue not recorded'}*")
            A("")
    if unfiled:
        A("## Unfiled")
        A("")
        A(f"*{len(unfiled)} papers* with no topic assigned.")
        A("")
        for p in unfiled:
            A(f"- [{esc(p.get('title')) or p['source']}](#{slug(p)}) — {cite(p)}")
        A("")

    # ── Part 2 ───────────────────────────────────────────────────────────────
    A("---")
    A("")
    A("# Part 2 — The papers")
    A("")
    for part in tax:
        A(f"## {part['letter']}. {part['name']}")
        A("")
        for t in part["topics"]:
            entries = by_topic.get(t["name"], [])
            if not entries:
                continue
            A(f"### {t['name']}")
            A("")
            for p in entries:
                A(f'<a id="{slug(p)}"></a>')
                A("")
                A(f"#### {esc(p.get('title')) or p['source']}")
                A("")
                venue = esc(p.get("venue")) or "venue not recorded"
                doi = esc(p.get("doi"))
                line = f"{cite(p)} · *{venue}*"
                # A missing DOI is stated, never invented (§3).
                line += (f" · [doi:{doi}](https://doi.org/{doi})" if doi
                         else " · no DOI recorded")
                A(line)
                A("")
                for label, key in (("Summary", "summary"), ("Limitations", "limitations")):
                    val = esc(p.get(key))
                    A(f"**{label}.** {val if val else '_Not written._'}")
                    A("")
                    if label == "Summary":
                        kp = p.get("key_points") or []
                        A("**Key points.**")
                        A("")
                        if kp:
                            for k in kp:
                                A(f"- {esc(k)}")
                        else:
                            A("- _Not written._")
                        A("")

    dest = resolve_out(args.out)
    dest.mkdir(parents=True, exist_ok=True)
    path = dest / f"{args.date}_reading_digest.md"
    assert not path.name.endswith("_literature_review.md"), \
        "would be picked up as the taxonomy by build.newest_review()"
    text = "\n".join(L).rstrip("\n") + "\n"
    path.write_text(text, encoding="utf-8")
    print(f"make_digest: wrote {path.relative_to(ROOT)}  ({len(text)//1024} KB)")
    print(f"make_digest: {len(papers)} papers · {n_top} topics · {len(tax)} parts"
          + (f" · {len(unfiled)} unfiled" if unfiled else ""))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
